/**:
  ros__parameters:
    uav_parameters:
      mass: 1.58                  # Kg
      arm_length: 0.215             # m
      num_of_arms: 4
      inertia:                     # Kg.m^2
        x: 0.08612
        y: 0.08962
        z: 0.16088
      moment_constant: 0.0205736     # m
      thrust_constant: 8.81026e-06   # N.s^2/rad^2
      max_rotor_speed: 1017        # rad/s
      gravity: 9.81                # m/s^2
      omega_to_pwm_coefficient:
        x_2: 0.000383914
        x_1: 0.567562
        x_0: 1021.01
      PWM_MIN: 1075
      PWM_MAX: 1950
      input_scaling: 1000
      zero_position_armed: 10